version: '2'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  service-account:
    build: service-account
    ports:
      - 6000:6000

  service-auth:
    build: service-auth
    ports:
      - 5000:5000

  monitoring:
    build: monitoring