logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

security:
  oauth2:
    resource:
      loadBalanced: true
      user-info-uri: http://service-auth:5000/uaa/users/current

spring:
  rabbitmq:
    host: rabbitmq
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true