spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth
    username: ${SERVICE_AUTH_DB_USER}
    password: ${SERVICE_AUTH_DB_PASSWORD}
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5

flyway:
  url: jdbc:mysql://127.0.0.1:3306/auth
  user: ${SERVICE_AUTH_DB_USER}
  password: ${SERVICE_AUTH_DB_PASSWORD}
  locations: classpath:db/migration
  enabled: true

server:
  context-path: /uaa
  port: 5000
